// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrtnpreotcryidsdxlpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydG5wcmVvdGNyeWlkc2R4bHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTgzOTEsImV4cCI6MjA3NDI5NDM5MX0.7X9pKA0BCKz7c24XREStjAIH-AZKco8oDBccZjq8Z4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});